---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# saasi

<!-- badges: start -->
<!-- badges: end -->

Ancestral state reconstruction method that accounts for variation in sampling
rate among locations.

## Installation

You can install the development version of saasi from
[GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("ivansg44/saasi")
```

## Examples

### Ancestral state reconstruction

```{r asr}
library(saasi)

phy <- readRDS(file.path("data", "two_sampled_states_phy.rds"))
params_df <- readRDS(file.path("data", "two_sampled_states_params_df.rds"))
q_matrix <- readRDS(file.path("data", "two_sampled_states_q_matrix.rds"))

options(scipen = 999)
# Probabilities of each node in `phy` being in state 1 or 2
saasi(phy, params_df, q_matrix, plot = TRUE, cex = 0.75)
```

### Simulate a birth/death/sampling tree

```{r sim_bds_tree}
library(saasi)

params_df <- readRDS(file.path("data", "three_sampled_states_params_df.rds"))
q_matrix <- readRDS(file.path("data", "three_sampled_states_q_matrix.rds"))

# Tree in `ape` `phylo` format; root state specified as 1
sim_bds_tree(params_df, q_matrix, 1)
```

### Estimate speciation/extinction rates

```{r mle_lm}
library(saasi)

phy <- readRDS(file.path("data", "three_sampled_states_phy.rds"))

# Estimate `lambda` and `mu` params for a phylogeny, by method of max likelihood
mle_lm(phy)
```
